project:
  type: website

website:
  title: ""
  reader-mode: true
  search: False
  navbar:
    left:
      - href: index.qmd
        text: About Me 
      - href: blog.qmd
        text: Daily Problems
    tools:
      - icon: github
        href: https://github.com/OmarHayat-DEV

  page-footer:
    center: 
      - text: "&copy Copyright 2024 | Omar Hayat | 2024-03-31 "


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


