project:
  type: website
  resources: files

website:
  title: ""
  search: False
  navbar:
    left:
      - href: index.qmd
        text: About Me 

  page-footer:
    center: 
      - text: "&copy Copyright 2024 | Omar Hayat | July 19th, 2024"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


