---
title: "Omar Hayat"
about:
  template: marquee
  links:
    - icon: file-earmark
      text: CV
    - icon: github
      text: Github
      href: https://github.com/OmarHayat-DEV
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/omarhayat1/
---
___
I am an incoming MMath in Computational Mathematics student at the University of Waterloo.

My supervisors are Dr. Giang Tran and Dr. Saeed Ghadimi. 

I obtained my BSc in Computer Science and Mathematics from the University of Ottawa.
#### Brief CV
___
##### Education 
  <span style="font-size: 0.85em;">
  **MMath Computational Mathematics** <br/>
   <span style="font-size:0.95em;">
   *University of  Waterloo* <br/> 
   *Sep 2024 --- Aug 2025*
   </span> 
</span> 

<span style="font-size:0.85em;">
**Honours BSc Computer Science and Mathematics** <br/>
 <span style="font-size:0.95em;">
 *University of Ottawa* <br/>
 *Sep 2018 --- May 2023*
 </span>
</span> 

___
##### Work Experience 
<span style="font-size:0.85em;">
**Data Engineering Intern**<br/>
 <span style="font-size:0.95em;">
 *National Research Council of Canada --- Automotive and Surface Transportation Centre* <br/>
 *May 2022 --- Dec 2022 | Ottawa, ON * 
 </span>
</span> 

<span style="font-size:0.85em;">
**Data Science Intern**<br/>
 <span style="font-size:0.95em;">
 *Financial Transactions and Reports Analysis Centre of Canada (FINTRAC)* <br/>
 *Sep 2021 --- Dec 2021 | Ottawa,ON *
 </span>
</span> 

<span style="font-size:0.85em;">
**Data Science Intern **<br/>
 <span style="font-size:0.95em;">
 *Novartis AG * <br/>
 *May 2020 --- Dec 2020 | Remote* 
 </span>
</span> 

___
##### Extra Curricular Experience
<span style="font-size:0.85em;">
**Software Engineering Team Lead**<br/>
 <span style="font-size:0.95em;">
 *Engineering Competition Team --- UO Supermileage* <br/>
 *Sep 2021 --- Sep 2022*
 </span>
</span> 

<span style="font-size:0.85em;">
**Printed Circuit Board Designer**<br/>
 <span style="font-size:0.95em;">
 *Engineering Competition Team --- UO Supermileage* <br/>
 *Jan 2019 --- Sep 2021*
 </span>
</span> 